name: Prepare release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'master'
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Validate input version format
        run: |
          if ! [[ ${{ inputs.version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+(-((alpha|beta)\.[0-9]+))?$ ]]; then
            echo "Error: Version must match semantic versioning pattern:"
            echo "  - x.y.z (e.g. 1.2.3)"
            echo "Got: ${{ inputs.version }}"
            exit 1
          fi

      - name: Update version in README
        run: |
          PATTERN='implementation("ru.stersh:subsonic-api:.*")'
          REPLACEMENT='implementation("ru.stersh:subsonic-api:${{ inputs.version }}")'
          sed -i "s/$PATTERN/$REPLACEMENT/" README.md

      - name: Update version in build.gradle.kts
        run: |
          cd library
          sed -i "s/version = .*/version = "${{ inputs.version }}"/" build.gradle.kts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: release ${{ inputs.version }}"
          branch: release-v${{ inputs.version }}
          delete-branch: false
          title: "chore: release ${{ inputs.version }}"
          base: master